(ops)添加cd工作流

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,3 +19,40 @@ steps:
     docker login -u $(aliusername) -p $(alipassword)  registry.cn-hangzhou.aliyuncs.com
     docker tag $(imageName):latest registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-app:latest
     docker push registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-app:latest
+
+- task: SSH
+  displayName: 'deploy to remote machine'
+  inputs:
+    sshEndpoint: 'huaweicloud'
+    runOptions: inline
+
+    inline: |
+     containers1=$(docker ps -q -a --filter name=kugga-web)
+     if test -n "$containers1"; then
+      docker rm -f $(docker ps -q -a --filter name=kugga-web) >> /dev/null 2>&1
+      rc=$?
+      if [[ $rc != 0 ]];
+      then
+       echo 'failed to remove container...'
+       exit $rc;
+      fi
+     fi
+     
+     docker login -u $(aliusername) -p $(alipassword)  registry.cn-hangzhou.aliyuncs.com
+     docker pull registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-app:latest >> /dev/null 2>&1
+     rc=$?
+     if [[ $rc != 0 ]];
+     then
+      echo 'failed to pull container...'
+      exit $rc;
+     fi
+     
+     docker run -d -p 567:80 --name=kugga-web --restart=always registry.cn-hangzhou.aliyuncs.com/ayang818/kugga-app:latest >> /dev/null 2>&1
+     rc=$?
+     if [[ $rc != 0 ]];
+     then
+      echo 'failed to run container...'
+      exit $rc;
+     fi
+     
+     echo 'success to start kugga-web'
